package types

type RequestType int

const (
	REQUEST_SOCKETS RequestType = iota
	REQUEST_ALL_ROOMS
	REQUEST_REMOTE_JOIN
	REQUEST_REMOTE_LEAVE
	REQUEST_REMOTE_DISCONNECT
	REQUEST_REMOTE_FETCH
	REQUEST_SERVER_SIDE_EMIT
	REQUEST_BROADCAST
	REQUEST_BROADCAST_CLIENT_COUNT
	REQUEST_BROADCAST_ACK
)
